# 2. Text Preprocessing (텍스트 전처리)  
part2

## 2-5. 정규 표현식(Regular Expression)


### 2-5-1. 정규 표현식 문법과 모듈 함수  
특수 문자
+ `.` : 임의의 문자('\n'은 제외) 1개
+ `?` : 앞의 문자 0개 or 1개  
+ `*` : 앞의 문자 0개 이상
+ `+` : 앞의 문자 1개 이상
+ `^` : 뒤의 문자열로 문자열 시작
+ `$` : 앞의 문자열로 문자열 끝  
+ `{숫자}` : 숫자만큼 반복
+ `{숫자1, 숫자2}` : [숫자1,숫자2] 만큼 반복  
+ `{숫자, }` : 숫자 이상만큼 반복  
+ `[문자]` : [amk] a or m or k
+ `[^문자]` : 문자 제외 문자 매치
+ `|` : [A|B] A 또는 B  
  
탈출 문자 
+ `\\\` : 역슬래쉬 자체
+ `\\d` : 모든 숫자, [0-9] 
+ `\\D` : 숫자제외 모든 문자, [^0-9]
+ `\\s` : 공백, [ \t\n\r\f\v]
+ `\\S` : 공백제외 모든 문자, [^\t\n\r\f\v]
+ `\\w` : 모든 문자 or 숫자, [a-zA-Z0-9]
+ `\\W` : 문자 또는 숫자가 아닌 문자 [^a-zA-Z0-9]  


### 2-5-2. 정규 표현식 실습 

In [ ]:
import re

In [ ]:
# . : 아무 문자 하나나
r=re.compile("a.c") # a_c, 

In [ ]:
r.search('kkk')

In [ ]:
r.search('abc')

<re.Match object; span=(0, 3), match='abc'>

In [ ]:
r.search('abcc')

<re.Match object; span=(0, 3), match='abc'>

In [ ]:
# ? : 앞 문자 0 or 1개
r=re.compile("ab?c")

In [ ]:
r.search('abc')

<re.Match object; span=(0, 3), match='abc'>

In [ ]:
r.search('ac')

<re.Match object; span=(0, 2), match='ac'>

In [ ]:
r.search('a3cc')

In [ ]:
# * : 앞 문자 0개 이상
r=re.compile('ab*c')

In [ ]:
r.search('abc')

<re.Match object; span=(0, 3), match='abc'>

In [ ]:
r.search('ac')

<re.Match object; span=(0, 2), match='ac'>

In [ ]:
r.search('aaa')

In [ ]:
# + : 앞 문자 1개 이상
r=re.compile('ab+c')

In [ ]:
r.search('abc')

<re.Match object; span=(0, 3), match='abc'>

In [ ]:
r.search('abbbc')

<re.Match object; span=(0, 5), match='abbbc'>

In [ ]:
r.search('ac')

In [ ]:
# ^ : 시작되는 문자열
r=re.compile('^ab')

In [ ]:
r.search('ac')

In [ ]:
r.search('cab')

In [ ]:
r.search('abc')

<re.Match object; span=(0, 2), match='ab'>

In [ ]:
# {숫자} : 앞문자 반복
r=re.compile('ab{2}c')

In [ ]:
r.search('abbc')

<re.Match object; span=(0, 4), match='abbc'>

In [ ]:
r.search('abbbc')

In [ ]:
# {숫자1, 숫자2} : [숫자1,숫자2] 만큼 반복
r=re.compile('ab{2,4}c')

In [ ]:
r.search('abc')

In [ ]:
r.search('abbc')

<re.Match object; span=(0, 4), match='abbc'>

In [ ]:
r.search('abbbbbc')

In [ ]:
# {숫자, } : 숫자 이상 반복
r=re.compile('ab{2,}c')

In [ ]:
r.search('abc')

In [ ]:
r.search('abbbc')

<re.Match object; span=(0, 5), match='abbbc'>

In [ ]:
# [] : 문자
r=re.compile('[abc]') #[a-c]

In [ ]:
r.search('zzz')

In [ ]:
r.search('azz')

<re.Match object; span=(0, 1), match='a'>

In [ ]:
r.search('zb')

<re.Match object; span=(1, 2), match='b'>

In [ ]:
r=re.compile('[a-z]')

In [ ]:
r.search('aBC')

<re.Match object; span=(0, 1), match='a'>

In [ ]:
# [^문자] : 문자 제외 모든 문자
r=re.compile('[^abc]')

In [ ]:
r.search('abc')

In [ ]:
r.search('a')

In [ ]:
r.search('d')

<re.Match object; span=(0, 1), match='d'>

In [ ]:
r.search('&')

<re.Match object; span=(0, 1), match='&'>

### 2-5-3. 정규 표현식 모듈 함수 예제

+ re.match(), re.search()  
    re.match()는 처음부터  
    re.search()는 중간도 ㄱㅊ

In [ ]:
r=re.compile('ab.')

In [ ]:
r.match('kkkkabc')

In [ ]:
r.search('kkkabc')

<re.Match object; span=(3, 6), match='abc'>

In [ ]:
r.match('abckkk')

<re.Match object; span=(0, 3), match='abc'>

+ re.split()  
    입력된 정규 표현식을 기준으로 문자열 분리

In [ ]:
text='사과 딸기 수박 메론 바나나'

In [ ]:
re.split(' ',text)

['사과', '딸기', '수박', '메론', '바나나']

In [ ]:
text="""사과
딸기
수박
메론
바나나"""

In [ ]:
re.split('\n',text)

['사과', '딸기', '수박', '메론', '바나나']

+ re.findall()

In [ ]:
text="""이름 : 김철수
전화번호 : 010 - 1234 - 1234
나이 : 30
성별 : 남"""

In [ ]:
re.findall('\d+',text)

['010', '1234', '1234', '30']

In [ ]:
re.findall('\d+','문자열입니다')

[]

+ re.sub()  
    문자열 찾아 다른 문자열로 대체

In [ ]:
text = "Regular expression : A regular expression, regex or regexp[1] (sometimes called a rational expression)[2][3] is, in theoretical computer science and formal language theory, a sequence of characters that define a search pattern."

In [ ]:
preproc_text=re.sub('[^a-zA-Z]',' ',text)
print(preproc_text)

Regular expression   A regular expression  regex or regexp     sometimes called a rational expression        is  in theoretical computer science and formal language theory  a sequence of characters that define a search pattern 


### 2-5-4. 정규 표현식 텍스트 전처리

In [ ]:
text="""100 John    PROF
101 James   STUD
102 Mac   STUD"""

In [ ]:
# 공백에서 스플릿
re.split('\s+',text) # 공백이 하나 이상

['100', 'John', 'PROF', '101', 'James', 'STUD', '102', 'Mac', 'STUD']

In [ ]:
# 숫자만 
re.findall('\d+',text)

['100', '101', '102']

In [ ]:
# 대문자만
re.findall('[A-Z]',text)

['J', 'P', 'R', 'O', 'F', 'J', 'S', 'T', 'U', 'D', 'M', 'S', 'T', 'U', 'D']

In [ ]:
# 직함만
re.findall('[A-Z]{4}',text)

['PROF', 'STUD', 'STUD']

In [ ]:
# 이름만
re.findall('[A-Z][a-z]+',text)

['John', 'James', 'Mac']

### 2-5-5. 정규 표현식을 이용한  토큰화  
`RegexpTokenizer` : 정규 표현식을 사용한 단어 토큰화 도구  
+ RegexpTokenizer() 안에 하나의 토큰으로 규정하기 원하는 정규식 넣어서 토큰화 수행

In [ ]:
from nltk.tokenize import RegexpTokenizer

text="Don't be fooled by the dark sounding name, \
Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop"

In [ ]:
# tokenizer1 : 문자 or 숫자 1개 이상 -> 하나의 토큰으로
tokenizer1=RegexpTokenizer('\w+')
print(tokenizer1.tokenize(text))

['Don', 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'Mr', 'Jone', 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']


In [ ]:
# tokenizer2 : 공백 기준 토큰화
tokenizer2=RegexpTokenizer('\s+',gaps=True) # gaps=True: 정규식을 기준으로
print(tokenizer2.tokenize(text))

["Don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name,', 'Mr.', "Jone's", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']


## 2-6. 정수 인코딩 (Integer Encoding)  
5000개의 단어가 등장한다면   
-> 빈도수로 정렬  
-> 1~5000번 mapping

### 2-6-1. Integer Encoding

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
# dictionary 사용
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
raw_text = "A barber is a person. \
a barber is good person.\
 a barber is huge person. \
 he Knew A Secret! \
 The Secret He Kept is huge secret. \
 Huge secret. \
 His barber kept his word. \
 a barber kept his word. \
 His barber kept his secret. \
 But keeping and keeping such a huge secret to himself was driving the barber crazy. \
 the barber went up a huge mountain."

In [ ]:
# 문장 토큰화 
s_tokens=sent_tokenize(raw_text)
print(s_tokens)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [ ]:
# vocab 딕셔너리 생성
vocab={}
preproc_sentences=[]
stop_words=set(stopwords.words('english'))

for s in s_tokens:
    w_tokens=word_tokenize(s) # 단어 토큰화
    
    result = []
    for w in w_tokens:
        w=w.lower() # 소문자로 통일
        if w not in stop_words: # 불용어 제거
            if len(w)>2: # 길이 기준으로 Cleaning
                result.append(w)
                if w not in vocab:
                    vocab[w]=0
                vocab[w]+=1

    preproc_sentences.append(result)

In [ ]:
print(preproc_sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [ ]:
print('단어집합 : ',vocab)

단어집합 :  {'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}


In [ ]:
# 딕셔너리 정렬
vocab_sorted=sorted(vocab.items(),key=lambda x:x[1],reverse=True)
print(vocab_sorted)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3), ('word', 2), ('keeping', 2), ('good', 1), ('knew', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)]


In [ ]:
# mapping
word2index={}

i=0
for (word,freq) in vocab_sorted: 
    if freq>1:
        i=i+1
        word2index[word]=i

In [ ]:
print(word2index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


In [ ]:
# 빈도수 상위 5개 단어만 남기고 삭제
size=5

## 희귀 단어 리스트
rare_words=[word for (word,rank) in word2index.items() if rank>size]
print(rare_words)

## 나머지 삭제
for word in rare_words:
    del word2index[word]
print(word2index)

['word', 'keeping']
{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [ ]:
# preproc_sentences를 인코딩하기
print(preproc_sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [ ]:
word2index['OOV']=len(word2index)+1
print(word2index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'OOV': 6}


In [ ]:
encoded_sentences=[]
for s in preproc_sentences:
    temp=[]
    for w in s:
        try:
            temp.append(word2index[w])
        except KeyError:
            temp.append(word2index['OOV'])
    encoded_sentences.append(temp)

In [ ]:
print(encoded_sentences)

[[1, 5], [1, 6, 5], [1, 3, 5], [6, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [6, 6, 3, 2, 6, 1, 6], [1, 6, 3, 6]]


In [ ]:
# Counter 사용
from collections import Counter

In [ ]:
print(preproc_sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [ ]:
# 단일 리스트로 바꾸기
word_list=sum(preproc_sentences,[])
print(word_list)

['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']


In [ ]:
import numpy as np
np.hstack(preproc_sentences)

array(['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge',
       'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret',
       'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept',
       'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge',
       'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge',
       'mountain'], dtype='<U8')

In [ ]:
vocab=Counter(word_list)
print(vocab)

Counter({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})


In [ ]:
print(vocab['barber'])

8


In [ ]:
size=5
vocab=vocab.most_common(size)
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [ ]:
word2index={}
i=0
for (word,freq) in vocab:
    i=i+1
    word2index[word]=i

In [ ]:
print(word2index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [ ]:
# NLTK의 FreqDist 사용하기
from nltk import FreqDist
word_list=np.hstack(preproc_sentences)
vocab=FreqDist(word_list)

In [ ]:
size=5
vocab=vocab.most_common(size)
print(vocab)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]


In [ ]:
word2index={word[0]:index+1 for index,word in enumerate(vocab)}
print(word2index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


## 2-6-2. 케라스의 텍스트 전처리

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
preproc_sentences=[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]

In [ ]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(preproc_sentences)

In [ ]:
print(tokenizer.word_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}


In [ ]:
print(tokenizer.word_counts)

OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])


In [ ]:
print(tokenizer.texts_to_sequences(preproc_sentences))

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [ ]:
size=5
tokenizer=Tokenizer(num_words=size+1) # 0번~5번 ->6개
tokenizer.fit_on_texts(preproc_sentences)

In [ ]:
print(tokenizer.word_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}


In [ ]:
print(tokenizer.word_counts)

OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])


In [ ]:
print(tokenizer.texts_to_sequences(preproc_sentences))

[[1, 5], [1, 5], [1, 3, 5], [2], [2, 4, 3, 2], [3, 2], [1, 4], [1, 4], [1, 4, 2], [3, 2, 1], [1, 3]]


In [ ]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(preproc_sentences)

In [ ]:
size=5
rare_words=[word for word,index in tokenizer.word_index.items() if index>size]

for word in rare_words:
    del tokenizer.word_index[word]
    del tokenizer.word_counts[word]

In [ ]:
print(tokenizer.word_index)
print(tokenizer.word_counts)
print(tokenizer.texts_to_sequences(preproc_sentences))

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}
OrderedDict([('barber', 8), ('person', 3), ('huge', 5), ('secret', 6), ('kept', 4)])
[[1, 5], [1, 5], [1, 3, 5], [2], [2, 4, 3, 2], [3, 2], [1, 4], [1, 4], [1, 4, 2], [3, 2, 1], [1, 3]]


In [ ]:
size=5
tokenizer=Tokenizer(num_words=size+2,oov_token='OOV')
tokenizer.fit_on_texts(preproc_sentences)

In [ ]:
print(tokenizer.word_index)
print(tokenizer.word_counts)
print(tokenizer.texts_to_sequences(preproc_sentences))

{'OOV': 1, 'barber': 2, 'secret': 3, 'huge': 4, 'kept': 5, 'person': 6, 'word': 7, 'keeping': 8, 'good': 9, 'knew': 10, 'driving': 11, 'crazy': 12, 'went': 13, 'mountain': 14}
OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])
[[2, 6], [2, 1, 6], [2, 4, 6], [1, 3], [3, 5, 4, 3], [4, 3], [2, 5, 1], [2, 5, 1], [2, 5, 3], [1, 1, 4, 3, 1, 2, 1], [2, 1, 4, 1]]


In [ ]:
print('OOV의 인덱스 : ',tokenizer.word_index['OOV'])

## 2-7. 패딩(Padding). 
길이가 같은 문서들은 병렬 연산이 가능함  
-> 길이를 맞춰주는 작업

### 2-7-1. Numpy로 패딩하기

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
preproc_sentences = [['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]

In [ ]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(preproc_sentences)
encoded=tokenizer.texts_to_sequences(preproc_sentences)
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [ ]:
max_len=max(len(item) for item in encoded)
print(f'최대 길이 : {max_len}')

최대 길이 : 7


In [ ]:
for s in encoded:
    while len(s)<max_len:
        s.append(0)
padded=np.array(encoded)
padded

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

### 2-7-2. 케라스 전처리 도구로 패딩하기

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
encoded=tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [ ]:
padded2=pad_sequences(encoded)
padded2

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]], dtype=int32)

In [ ]:
padded2=pad_sequences(encoded,padding='post')
padded2

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]], dtype=int32)

In [ ]:
(padded==padded2).all()

True

In [ ]:
padded=pad_sequences(encoded,padding='post',maxlen=5)
padded

array([[ 0,  0,  0,  0,  0],
       [ 5,  0,  0,  0,  0],
       [ 5,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 3,  2,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 6,  0,  0,  0,  0],
       [ 6,  0,  0,  0,  0],
       [ 2,  0,  0,  0,  0],
       [ 3,  2, 10,  1, 11],
       [ 3, 13,  0,  0,  0]], dtype=int32)

In [ ]:
padded=pad_sequences(encoded,padding='post',truncating='post',maxlen=5)
padded

array([[ 1,  5,  0,  0,  0],
       [ 1,  8,  5,  0,  0],
       [ 1,  3,  5,  0,  0],
       [ 9,  2,  0,  0,  0],
       [ 2,  4,  3,  2,  0],
       [ 3,  2,  0,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  2,  0,  0],
       [ 7,  7,  3,  2, 10],
       [ 1, 12,  3, 13,  0]], dtype=int32)

In [ ]:
last_value=len(tokenizer.word_index)+1
print(last_value)

14


In [ ]:
padded=pad_sequences(encoded,padding='post',value=last_value)
padded

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]], dtype=int32)

## 2-8. 원핫인코딩

In [ ]:
!pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 19.4 MB 5.2 MB/s 
     |████████████████████████████████| 465 kB 52.8 MB/s 


In [ ]:
from konlpy.tag import Okt

okt=Okt()
tokens=okt.morphs('나는 자연어 처리를 배운다')
print(tokens)

['나', '는', '자연어', '처리', '를', '배운다']


In [ ]:
word2index={word:index for index,word in enumerate(tokens)}
print(word2index)

{'나': 0, '는': 1, '자연어': 2, '처리': 3, '를': 4, '배운다': 5}


In [ ]:
def one_hot_encoding(word,word2index):
    one_hot_vector =[0]*(len(word2index))
    index=word2index[word]
    one_hot_vector[index]=1
    return one_hot_vector

In [ ]:
one_hot_encoding('자연어',word2index)

[0, 0, 1, 0, 0, 0]

## 2-10. 한국어 전처리 패키지

### 2-10-1. PyKoSpacing  
띄어쓰기가 되어있지 않은 문장을 띄어쓰기한 문장으로 변환하는 패키지  
-> 대용량 코퍼스를 학습하여 만들어진 꽤 괜찮은 딥러닝 모델

In [ ]:
!pip install git+https://github.com/haven-jeon/PyKoSpacing.git

In [2]:
string='김철수는 극중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연재(김광수 분)를 찾으러 속세로 내려온 인물이다.'

In [3]:
new_string=string.replace(' ','')
print(new_string)

김철수는극중두인격의사나이이광수역을맡았다.철수는한국유일의태권도전승자를가리는결전의날을앞두고10년간함께훈련한사형인유연재(김광수분)를찾으러속세로내려온인물이다.


In [5]:
from pykospacing import Spacing

spacing=Spacing()
spacing_string=spacing(new_string)

1/1 [==============================] - 1s 759ms/step


In [6]:
print(new_string)
print(spacing_string)

김철수는극중두인격의사나이이광수역을맡았다.철수는한국유일의태권도전승자를가리는결전의날을앞두고10년간함께훈련한사형인유연재(김광수분)를찾으러속세로내려온인물이다.
김철수는 극중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연재(김광수 분)를 찾으러 속세로 내려온 인물이다.


### 2-10-2. Py-Hanspell  
네이버 한글 맞춤법 검사기를 바탕으로 만들어진 패키지

In [ ]:
!pip install git+https://github.com/ssut/py-hanspell.git

In [13]:
from hanspell import spell_checker

string="맞춤법 틀리면 외 않되? 쓰고싶은대로쓰면돼지 "
spelled_string=spell_checker.check(string)
hanspell_string=spelled_string.checked

In [14]:
print(hanspell_string)

맞춤법 틀리면 왜 안돼? 쓰고 싶은 대로 쓰면 되지


In [15]:
# 띄어쓰기도 수정해줌
spelled_string=spell_checker.check(new_string)
hanspell_string=spelled_string.checked
print(spacing_string)
print(hanspell_string)

김철수는 극중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연재(김광수 분)를 찾으러 속세로 내려온 인물이다.
김철수는 극 중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연제(김광수 분)를 찾으러 속세로 내려온 인물이다.


### 2-10-3. SOYNLP를 이용한 토큰화  
품사태깅, 단어 토큰화 지원하는 토크나이저  
-> 비지도학습으로 토큰화 진행  
+ 자주 등장하는 단어들을 단어로 분석함  
+ 응집확률(cohension) & 브랜칭 엔트로피(branching entropy)

In [ ]:
!pip install konlpy
!pip install soynlp

In [17]:
# 기존 형태소 분석기의 문제점 - 신조어
from konlpy.tag import Okt
tokenizer=Okt()

string='에이비식스 이대휘 1월 최애돌 기부 요정'
print(tokenizer.morphs(string))

['에이', '비식스', '이대', '휘', '1월', '최애', '돌', '기부', '요정']


특정 데이터에서 특정 문자열끼리 등장 빈도 높고,  
앞 뒤 조사 or 완전 다른 단어가 등장하는 것을 고려하여  
해당 문자열을 형태소로 판단해보자

In [19]:
# 학습하기
import urllib.request
from soynlp import DoublespaceLineCorpus
from soynlp.word import WordExtractor

urllib.request.urlretrieve("https://raw.githubusercontent.com/lovit/soynlp/master/tutorials/2016-10-20.txt", filename="2016-10-20.txt")

('2016-10-20.txt', <http.client.HTTPMessage at 0x7fb907975cd0>)

In [20]:
# 훈련 데이터를 다수의 문서로 분리
corpus=DoublespaceLineCorpus('2016-10-20.txt')
len(corpus)

30091

3만개 정도의 문서로 분리됨

In [25]:
# 몇개만 확인해보기
i=0
for document in corpus:
    if len(document)>0:
        print(document)
        print('-'*10)
        i+=1
    if i==3:
        break

19  1990  52 1 22
----------
오패산터널 총격전 용의자 검거 서울 연합뉴스 경찰 관계자들이 19일 오후 서울 강북구 오패산 터널 인근에서 사제 총기를 발사해 경찰을 살해한 용의자 성모씨를 검거하고 있다 성씨는 검거 당시 서바이벌 게임에서 쓰는 방탄조끼에 헬멧까지 착용한 상태였다 독자제공 영상 캡처 연합뉴스  서울 연합뉴스 김은경 기자 사제 총기로 경찰을 살해한 범인 성모 46 씨는 주도면밀했다  경찰에 따르면 성씨는 19일 오후 강북경찰서 인근 부동산 업소 밖에서 부동산업자 이모 67 씨가 나오기를 기다렸다 이씨와는 평소에도 말다툼을 자주 한 것으로 알려졌다  이씨가 나와 걷기 시작하자 성씨는 따라가면서 미리 준비해온 사제 총기를 이씨에게 발사했다 총알이 빗나가면서 이씨는 도망갔다 그 빗나간 총알은 지나가던 행인 71 씨의 배를 스쳤다  성씨는 강북서 인근 치킨집까지 이씨 뒤를 쫓으며 실랑이하다 쓰러뜨린 후 총기와 함께 가져온 망치로 이씨 머리를 때렸다  이 과정에서 오후 6시 20분께 강북구 번동 길 위에서 사람들이 싸우고 있다 총소리가 났다 는 등의 신고가 여러건 들어왔다  5분 후에 성씨의 전자발찌가 훼손됐다는 신고가 보호관찰소 시스템을 통해 들어왔다 성범죄자로 전자발찌를 차고 있던 성씨는 부엌칼로 직접 자신의 발찌를 끊었다  용의자 소지 사제총기 2정 서울 연합뉴스 임헌정 기자 서울 시내에서 폭행 용의자가 현장 조사를 벌이던 경찰관에게 사제총기를 발사해 경찰관이 숨졌다 19일 오후 6시28분 강북구 번동에서 둔기로 맞았다 는 폭행 피해 신고가 접수돼 현장에서 조사하던 강북경찰서 번동파출소 소속 김모 54 경위가 폭행 용의자 성모 45 씨가 쏜 사제총기에 맞고 쓰러진 뒤 병원에 옮겨졌으나 숨졌다 사진은 용의자가 소지한 사제총기  신고를 받고 번동파출소에서 김창호 54 경위 등 경찰들이 오후 6시 29분께 현장으로 출동했다 성씨는 그사이 부동산 앞에 놓아뒀던 가방을 챙겨 오패산 쪽으로 도망간 후였다  김 경위는 오패산 터널 입구 오른쪽

soynlp는 학습 기반의 토크나어저 -> 학습 과정 필요함  
`응집확률` & `브랜칭 엔트로피 단어 점수표` 만들기

In [26]:
word_extractor=WordExtractor()
word_extractor.train(corpus)
word_score_table=word_extractor.extract()

training was done. used memory 1.851 Gb
all cohesion probabilities was computed. # words = 223348
all branching entropies was computed # words = 361598
all accessor variety was computed # words = 361598


In [28]:
print(len(word_score_table))

97765


9만개의 단어

+ SOYNLP의 응집확률 (Cohesion probability)  
값이 높을 수록 하나의 단어일 가능성이 높다는 말  
즉, 하나의 문자열로 __붙어다닐 확률이 높다__

In [30]:
word_score_table['반포한'].cohesion_forward

0.08838002913645132

In [31]:
word_score_table['반포한강'].cohesion_forward

0.19841268168224552

In [32]:
word_score_table['반포한강공'].cohesion_forward

0.2972877884078849

In [33]:
word_score_table['반포한강공원'].cohesion_forward

0.37891487632839754

In [34]:
word_score_table['반포한강공원에'].cohesion_forward

0.33492963377557666

낮아짐 -> '반포한강공원'까지 하나의 단어로 보자